### ISSUE TITLE
pify-ing a function with an error callback

### ISSUE THREAD

**Issue by williamboman** [sindresorhus/pify#12]
e.g. [Navigator.getUserMedia() [deprecated]](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia) uses this method of error handling, taking a separate callback for error handling. I couldn't find an option for these kinds of callback functions?

**Comment by sindresorhus** [comment]
Not interested in supporting such an obscure use-case. You can easily wrap it in a Promise manually. Also, that API is deprecated, so not sure why you're even using it.

**Comment by williamboman** [comment]
>Not interested in supporting such an obscure use-case. 

Yeah, it's very corner case.

>Also, that API is deprecated, so not sure why you're even using it.

Not really that deprecated, I just added the `[deprecated]` tag to point out it officially is. I mean Chrome beta channel has not even implemented `getUserMedia` on `navigator.mediaDevices` yet, afaik.
