### ISSUE TITLE
How to use with methods of objects?

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/pify#13]
I'm using pify successfully for modules and standalone functions, but how can it be used for methods of objects? I tried it with the `knox` module https://www.npmjs.com/package/knox but am getting an error `client.putFile is not a function` even though if I remove pify and `await` and add back the `callback(err, res)` as the last argument to client.putFile it works fine.

Am I doing it wrong?

```
const client = pify(knox.createClient({key: '...', secret: '...', bucket: '...', port: ... }));
await client.putFile('...', '...');
```

The knox page shows it's normally called like this

```
client.putFile('my.json', '/user.json', function(err, res){
  // Always either do something with `res` or at least call `res.resume()`. 
});
```

**Comment by SamVerschueren** [comment]
```js
pify(client.putFile.bind(client))(), 'my.json', '/user.json')
    ...
```
