### ISSUE TITLE
Consider supporting prototype methods

### ISSUE THREAD

**Issue by kevinoid** [sindresorhus/pify#14]
Any chance you would be willing to consider supporting `pify`-ing the prototypally-inherited methods of passed objects?

The main issue that I'm trying to solve is that code such as:

``` javascript
var lovebug = pify(new Car("Herbie"));
```

works if the `Car` constructor sets/copies/binds methods to `this`, but not if the methods are inherited via `prototype`.  So, unless I've missed something, `pify` users must either depend on the implementation of `Car` or roll their own method iteration wrapper for `pify` (and/or `pify` the prototype, then `pify` any methods set by the constructor).

If `pify`-ing inherited methods sounds agreeable but you'd need a PR to consider, I can work one up.  I would envision the methods being copied from the prototype to the new target object if a boolean option is set, but alternatives would be fine with me.

Thanks for considering,
Kevin

**Comment by sindresorhus** [comment]
Not something I personally need, but I can see it being useful for many, so PR welcome :) Should be a boolean option that is `false` by default.

**Comment by kevinoid** [comment]
Great, thanks!  I'll see what I can do.

**Comment by schnittstabil** [comment]
@kevinoid I assume we only consider *Enumerable* and *Inherited Enumerable* properties. In that case  I think it is sufficient to *choose* [`Object.keys` or `for…in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#Detection_Table) depending on your option at [index.js#L59](https://github.com/sindresorhus/pify/blob/master/index.js#L59).

**Comment by kevinoid** [comment]
@schnittstabil I agree, that sounds like the right behavior and implementation to me.  Thanks.

Feel free to do the PR if you are strongly motivated, I'm not picky about it.   Otherwise I should have some time to hammer it out later today.

**Comment by schnittstabil** [comment]
Sorry @kevinoid, I do neither see the need for that option nor have much time to implement it.
