### ISSUE TITLE
Support functions that don't pass an error to callback

### ISSUE THREAD

**Issue by bored** [sindresorhus/pify#15]
I've tried to use `pify` with [`Inquirer.js`](https://github.com/SBoudrias/Inquirer.js), it works, but the behavior is not the expected one.
``` js
const inquirer = pify(require('inquirer'));

inquirer.prompt([ questions ]).then((answers) => {
  console.log('Then:', answers);
}).catch((error) => {
  console.log('Catch:', error);
});
```
The output is `Catch: { Answers }`, this is because `inquirer` doesn't call the callback function with an error as the first argument, it just passes the `Answers` object as far as I know.

I think that there are two ways to solve this, an option or check if the first argument is an instance of `Error`.

Do you want to support this case?

**Comment by sindresorhus** [comment]
No, tell the author to use the Node.js error first convention.

You can however use https://github.com/samverschueren/rfpify.
