### ISSUE TITLE
the original `options` object is altered

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/pify#21]
The [options](https://github.com/sindresorhus/pify/blob/master/index.js#L40-L41) object is altered. I think it's better to use `object-assign` here.

Didn't create a PR immediately because I don't know if you want a dependency for such a small improvement as `pify` is dependency-less at the moment.

**Comment by sindresorhus** [comment]
Just change `opts.exclude = opts.exclude || [/.+Sync$/];` to use a variable instead of overriding the prop.

**Comment by SamVerschueren** [comment]
👍
