### ISSUE TITLE
Methods for keeping this

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/pify#23]
I find that I quite often need to preserve `this` when calling functions that takes callbacks. I have used something similar to the code below, but I would like to hear what you think of the matter.

Is there an easy way to support this use case?

```javascript
function promise (obj, fn) {
  return pify(obj[fn]).bind(obj)
}

await promise(linus, 'walk')(100, 'miles')
console.log('Linus walked 100 miles')

// vs.

linus.walk(100, 'miles', () => console.log('Linus walked 100 miles'))
```

**Comment by SamVerschueren** [comment]
Just use bind directly.

```js
await pify(linus.walk.bind(linux))(100, 'miles');
```

**Comment by LinusU** [comment]
That's true, I guess that it would be even nicer if pify supported it out of the box though. Maybe it's outside the scope though...

```js
await pify(linus, 'walk')(100, 'miles')
```

**Comment by sindresorhus** [comment]
@LinusU How would it know what to bind to? You would have had to pass the `this` in anyways.

**Comment by SamVerschueren** [comment]
@sindresorhus He wants that this example

```js
await pify(linus, 'walk')(100, 'miles')
```

binds the `walk` method to the `linux` object and thus to itself. But this was discussed in the past if I'm not mistaken.

**Comment by sindresorhus** [comment]
Yeah, not worth saving just a few characters. Using `bind` is a lot clearer too.

**Comment by LinusU** [comment]
Yes, what @SamVerschueren said, I should have been more clear.

I don't know if it's the cleanest approach, my main goal is just to keep the code clean and readable. I guess that we are at a point where many libraries are transitioning into promises, but it will probably be a long time until we are all the way there.

The problem I see with doing, e.g. `pify(fs.readFile)` is that I make an assumption that `readFile` doesn't use `this`. It seems like this will creep up to bite me at some point, which is why I would prefer to solve it somehow...

The function bind operator could solve this by using `pify(::fs.readFile)`, but that isn't nowhere near ready though :)

**Comment by SamVerschueren** [comment]
With using `bind`, you can bind the method to whatever you want so it's much more flexible and it's clear for everyone that it is bound to the object you pass in.

> I make an assumption that `readFile` doesn't use `this`. It seems like this will creep up to bite me at some point.

Your tests should catch that.

**Comment by sindresorhus** [comment]
I've rarely encountered the need to use `bind` though. Most API's in the Node.js world are luckily not using `this`.

**Comment by LinusU** [comment]
> I've rarely encountered the need to use `bind` though. Most API's in the Node.js world are luckily not using `this`.

True, I guess that this is good enough for now 👍 thanks for the discussion
