### ISSUE TITLE
Does not set default export

### ISSUE THREAD

**Issue by cstruct** [sindresorhus/pify#24]
At the moment this library is kind of ugly to use with the ES6 import syntax.

The current required syntax is:
```javascript
import * as pify from 'pify' 
```

Expected syntax
```javascript
import pify from pify
```

**Comment by kevva** [comment]
Then something is wrong with your code. Both me and @sindresorhus are using `pify` with ES2015 modules syntax in many repositories https://github.com/search?q=import+pify+user%3Asindresorhus&type=Code&utf8=%E2%9C%93.

**Comment by SamVerschueren** [comment]
Are you using TypeScript or Babel? Typescript requires the `import * as pify from` syntax. In order to let that work every module should export a `default` property.

**Comment by cstruct** [comment]
Thank you for a quick response! Not quoting was a typo.

I've had this issue on my todo list to report for a while and forgot that it's from typescript I noticed this.
