### ISSUE TITLE
Callback as first argument

### ISSUE THREAD

**Issue by screendriver** [sindresorhus/pify#30]
Is it possible to `pify` following function?

```js
doIt(callback, options);
```

I have a library where the `callback` is the first argument and the second one is `options` (usually in most API's it is inverted)

**Comment by screendriver** [comment]
> That API is really bad to be honest

Yes that's true. Unfortunately it's a external dependency that I have to use because there is no alternative out there. I try to write a little wrapper. Thank you.

**Comment by sindresorhus** [comment]
`lodash.flip()` is great for this.

**Comment by screendriver** [comment]
Wohoo `lodash.flip()` was unknown for me so far. Exactly what I'm looking for. Thank you!
