### ISSUE TITLE
Add option to support non-error-first APIs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pify#31]
Initially, I didn't want this as it's a bad practise, so I asked @SamVerschueren to [make a module](https://github.com/SamVerschueren/rfpify).

After using `pify` for a good while, I've needed it more often than I would have liked, with a few Node.js API's (fs.exists), events, Chrome extension API's, and browser API's.

Instead of pretty much duplicating most of the code here into `rfpify`, I think we should add an option for it here instead.

@SamVerschueren Thoughts?

**Comment by SamVerschueren** [comment]
I almost never have to use rfpify to be honest. But I'm not using as much obscure API'S as you do :p. So yes, it might be easier to add an option here.

**Comment by kevva** [comment]
> I almost never have to use `rfpify` to be honest.

Me neither. Only if I need to catch some event when testing.

**Comment by iamale** [comment]
[WebTorrent][1] uses this sometimes:

```js
client.add(magnetURI, function (torrent) {  // no error parameter
  // Got torrent metadata!
  console.log('Client is downloading:', torrent.infoHash)
})
```

[1]: https://github.com/feross/webtorrent

**Comment by jdalton** [comment]
Just got bit by `exists`.
