### ISSUE TITLE
pify for gm doesn't seems to be working

### ISSUE THREAD

**Issue by kdybicz** [sindresorhus/pify#36]
Hi,

I'm trying to fix AVA tests for some [functionality](https://github.com/ysugimoto/aws-lambda-image/blob/master/test/resize-jpeg.js#L37) and I need to Promisify `gm(...).size()` function. Unfortunately I'm not able to do that properly: 

```
const out = await pify(gm(image.data).size());
console.log("gm output: " + out.width);
---
  gm output: undefined
```

```
const out = await pify(gm(image.data).size)();
console.log("gm output: " + out.width);
---
  1 failed

  resize-jpeg › Resize JPEG with jpegoptim
  Error: Cannot read property 'size' of undefined
    proto.(anonymous function) (node_modules/gm/lib/getters.js:47:20)
    node_modules/pify/index.js:29:7
    node_modules/pify/index.js:12:10
    ret (node_modules/pify/index.js:56:34)
    Test.<anonymous> (test/resize-jpeg.js:37:20)
    Generator.next (<anonymous>)
```

```
const out = await pify(gm(image.data).size.bind(gm))();
console.log("gm output: " + out.width);
---
  1 failed

  resize-jpeg › Resize JPEG with jpegoptim
  Error: Cannot read property 'size' of undefined
    proto.(anonymous function) (node_modules/gm/lib/getters.js:47:20)
    node_modules/pify/index.js:29:7
    node_modules/pify/index.js:12:10
    ret (node_modules/pify/index.js:56:34)
    Test.<anonymous> (test/resize-jpeg.js:37:20)
    Generator.next (<anonymous>)
```

```
const out = await pify(gm(image.data)).size();
console.log("gm output: " + out.width);
---
  1 failed

  resize-jpeg › Resize JPEG with jpegoptim
  Error: pify(...).size is not a function
    Test.<anonymous> (test/resize-jpeg.js:37:43)
    Generator.next (<anonymous>)
```

So, my question is: if it's possible to `pify` `gm` and if so, I would like to know how?

**Comment by SamVerschueren** [comment]
Try this

```is
const image = gm(...);

pify (image.bind (image))
```

**Comment by kdybicz** [comment]
Doesn't work:
```
  1 failed

  resize-jpeg › Resize JPEG with jpegoptim
  Error: image.bind is not a function
    Test.<anonymous> (test/resize-jpeg.js:39:32)
    Generator.next (<anonymous>)
```
neither does **Example 3**.

**Comment by SamVerschueren** [comment]
Oh yes off course. You have to pify pity the write function, not the others.

```js
const image = gm(…).size(100, 100);

pify(image.write.bind (image))().then(...);
```

**Comment by schnittstabil** [comment]
Your first and your second outputs show, that `gm(image.data)` returns `undefined`:
```
const out = await pify(gm(image.data).size)();
const out = await pify(gm(image.data).size.bind(gm))();
---
  Error: Cannot read property 'size' of undefined
```

At least these issues are unrelated to `pify`. 

---

About your third example:

```
const out = await pify(gm(image.data)).size();
---
  Error: pify(...).size is not a function
```

I cannot guess what `size` is: a number or a string or …? – @kdybicz Do you mind investigating the type and value of `size`?

**Comment by kdybicz** [comment]
`size` is a function http://aheckmann.github.io/gm/docs.html#getters

> gm(image.data) returns undefined

This one occures only when using `pify()`.

```
console.log("Plain gm: " + gm(image.data));
console.log("Type of gm.size: " + typeof gm(image.data).size);
const out = await pify(gm(image.data).size)();
---
Plain gm: [object Object]
Type of gm.size: function

  1 failed

  resize-jpeg › Resize JPEG with jpegoptim
  Error: Cannot read property 'size' of undefined
    proto.(anonymous function) (node_modules/gm/lib/getters.js:47:20)
    node_modules/pify/index.js:29:7
    node_modules/pify/index.js:12:10
    ret (node_modules/pify/index.js:56:34)
    Test.<anonymous> (test/resize-jpeg.js:40:20)
    Generator.next (<anonymous>)
```

**Comment by schnittstabil** [comment]
Maybe you want to try this:
```js
const img = gm(image.data);
const out = await pify(img.size.bind(img))(); // <-- bind to img, not to gm!
```

**Comment by kdybicz** [comment]
Unfortunately this doesn't seems to be working, I'm getting:
```
  1 failed

  resize-jpeg › Resize JPEG with jpegoptim
  Error: Cannot convert undefined or null to object
    Function.keys (<anonymous>)
    module.exports (node_modules/pify/index.js:59:16)
    gmP (test/resize-jpeg.js:11:26)
    Test.<anonymous> (test/resize-jpeg.js:39:20)
    Generator.next (<anonymous>)
```

**Comment by schnittstabil** [comment]
> ```js
> const img = gm(image.data);
> const out = await pify(img.size.bind(img))(); // <-- bind to img, not to gm!
> ```

@kdybicz Above works as expected. 

As a #16 workaround, I suggest a small helper function:
```js
const bind = obj => {
    for (const key in obj) {
        const val = obj[key];

        if (typeof val === 'function') {
            obj[key] = val.bind(obj);
        }
    }

    return obj;
};

const gmP = (...args) => pify(bind(gm(...args)));
```

By the way, your tests have additional issues (see https://github.com/secretescapes/aws-lambda-image/pull/1):
* `async/await` and callback style are unfortunately mixed; thus your assertions are not executed (https://github.com/schnittstabil/aws-lambda-image/commit/b6c14dc713f084ef788229a9af73962e268abb3b reveals that)
* cleanup is done with within the test functions (https://github.com/schnittstabil/aws-lambda-image/commit/f1cd0a0c863e5ab92d3b32a8ee88e704a8a5e16c shows a better alternative)

**Comment by schnittstabil** [comment]
I'm closing this, because it is a #16 duplicate.

**Comment by kdybicz** [comment]
This is my approach to solving this issue https://github.com/ysugimoto/aws-lambda-image/pull/87/files but I will for sure take a look at your proposal. Thanks!

**Comment by schnittstabil** [comment]
Btw, [`bind-all`](https://github.com/segmentio/bind-all/blob/master/lib/index.js#L7-L13) provides the same functionality as my `bind` helper above:

```js
const bindAll = require('bind-all');

const gmP = (...args) => pify(bindAll(gm(...args)));

test("Resize JPEG with cjpeg", async t => {
    //…
    const out = await gmP(destPath).size();
    t.is(out.width, 200);
});
```

**Comment by kdybicz** [comment]
Thanks to your advice I did end up with code, that is working perfectly fine! https://github.com/secretescapes/aws-lambda-image/blob/improving-tests-quality-v2/test/resize-jpeg.js
