### ISSUE TITLE
Accessing the synchronous return value of a pify'd function

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/pify#38]
Is there a way to access the synchronous return value of a pify'd function? For example:
````js
const socket = require('dns-socket')();
const pify = require('pify');

pify(socket.query.bind(socket))({
  questions: [{ type: 'A', name: 'google.com'}]
}, 53, '8.8.8.8').then(console.log);
````

`socket.query` returns a [query id](https://github.com/mafintosh/dns-socket#var-id--socketqueryquery-port-host-callback), but there's no way to access it when used with pify, right?

**Comment by sindresorhus** [comment]
Hmm, haven't seen much of this kind of thing, so not sure whether it's worth bothering supporting it, but could maybe attach a property on the promise with the returned value.

**Comment by silverwind** [comment]
Would it work like this?

```js
const promise = pify(fn)(args);
const id = promise.returnValue;
promise.then(doneFn);
```

That's quite ugly. Probably better to just do callback-style in that case.

**Comment by sindresorhus** [comment]
Yes. Do you have a better suggestion on how it could look?

**Comment by silverwind** [comment]
Only this, but I don't think it will work with `await`:

```js
const id = pify(fn)(args).then(doneFn).returnValue
```

**Comment by sindresorhus** [comment]
That looks even weirder and you couldn't easily use `catch()`. I think this is one of those times where it makes sense to custom-wrap it in a promise using `new Promise()`. Alternativelt, you could use [`p-cancelable`](https://github.com/sindresorhus/p-cancelable) to support canceling the promise by handling the `id` and calling `socket.cancel(id)`.

**Comment by silverwind** [comment]
It wasn't neccessary in my case after all. I'll close this as it seems sync return values won't play nice with `await` syntax at all, so they are better avoided altogether.
