### ISSUE TITLE
Take advantage of `util.promisify()` if it lands in Node.js

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pify#41]
Just opening this so I don't forget. `util.promisify()` can interact directly with the V8 API, so it doesn't create closures and will be faster than userland implementations.

https://github.com/nodejs/node/pull/12442

**Comment by addaleax** [comment]
@sindresorhus Don’t forget to benchmark, though. ;) I think the real advantage of `util.promisify` will be that Node core can specify custom implementations that use the promise directly (at least at some point in the future), instead of just wrapping the callback version.

I’ve tried some ad-hoc benchmarking, and the current way `util.promisify` is implemented doesn’t actually seem to perform very differently from the naïve way to wrap callback-taking functions.

**Comment by malixsys** [comment]
https://github.com/nodejs/node/commit/99da8e8e02a874a0a044889f863c45700509d02c

**Comment by hanford** [comment]
It landed today 🎉

**Comment by mikaturk** [comment]
using pify until Node 8 LTS :)
damn LTS schedules :(
can't even use async functions, have to compile :(

**Comment by bfred-it** [comment]
1. `pify` sounds like a ponyfill for `util.promisify`; as such:
  > Ponyfills should never use the native API, even if available
  > Source: [ponyfill.com](https://github.com/sindresorhus/ponyfill#ponyfill)
2. As #49 said, catching edge cases and differences between the two APIs may not be worth the effort.
3. Doesn't `util.promisify` effectively replace `pify`? Why use `pify` at all if `util.promisify` is available?

**Comment by pi0** [comment]
@sindresorhus I've proposed #68 to use native `Util.promisify` when possible. Which is also published as a temporary npm package [pify-native](https://github.com/blindmedia/pify-native) for those who wish to test it at production before this merge.

@addaleax I've implemented a [benchmark suite](https://github.com/blindmedia/pify-native/blob/master/bench.js) to see how perf differs. But [results](https://github.com/blindmedia/pify-native/blob/master/bench.md) shows that `pify`'s approach currently is faster. (Wondering if i made a proper benchmark script 🤔). /cc @jdalton

**Comment by sindresorhus** [comment]
I have decided not to do this: https://github.com/sindresorhus/pify/pull/68#issuecomment-473507955
