### ISSUE TITLE
Instead of multiArgs option, why not just detect multiple arguments?

### ISSUE THREAD

**Issue by mattflix** [sindresorhus/pify#45]
Instead of having to figure out and pass ```{ multiArgs: true }``` ahead of time, why not just have the internal callback check the number of arguments passed at runtime and then resolve the ```Promise``` either with an array (of multiple arguments) or the single argument itself?

Like so (shown here in ES6 syntax):

```javascript
function callback(error, ...args) {
    if (error != null) {
        reject(error);
    }
    else if (args.length > 1) {
        resolve(args); // multiple
    }
    else {
        resolve(args[0]); // single
    }
}
```

Note that the final ```else```-clause works correctly for either one or zero arguments, naturally passing ```undefined``` for the latter.

This would make it simple to apply ```pify()``` to an entire module where some of the callbacks supply multiple arguments and some don't.  Also, this would just make ```pify``` even easier to use in general, because the right thing would be done automatically and predictably -- if the callback has multiple arguments, you will get an array from the ```Promise```.

There is a small chance that some API that emits an array as the sole argument to some callback would appear ambiguous with the multi-argument case, but in practice I think this potential ambiguity is very small to non-existent.  Most APIs always invoke callbacks in a uniform manner, and so most handlers will be hard-coded to expect an array (multiple arguments) or not (single argument).  Single vs. multiple argument callback behavior is typically not "dynamic".

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/pify/issues/5 for context on why the implicit behavior is a bad idea.
