### ISSUE TITLE
Pify fails where normal new Promise() works

### ISSUE THREAD

**Issue by manuelnaturalcycles** [sindresorhus/pify#47]
Hej, I am so sorry to bother you with this, I love Pify as it is saving me a lot of code when working with non-pified libraries like braintree-web and braintree-web-drop-in.

Unfortunately there is a specific method that fails in a really weird way when I pify it.

The traditional wrapper works. I was expecting pify to work wherever a wrapper works.

I know this looks really in the air and not very specific but if you could help me understand it a bit I can provide you with all other information/time needed to debug this.

Thanks so much.

```
  async payDropIn (dropIn: DropInInstance): Promise<any> {
    // pified version does not work, catches error, looking at the library's code
    // it seems as if some context was lost?
    return pify(dropIn.requestPaymentMethod)()
      .then((payload) => {
        alert(payload.nonce)
      })
      .catch((er) => {
        alert(er) <-- ends up here
      })

    // typical wrap works. it throws no error and alerts the string it should
    return new Promise<DropInInstance>((resolve, reject) => {
      dropIn
        .requestPaymentMethod((err, payload) => {
          if (err) {
            console.error('Error requesting payment method in drop in ui ', err)
            reject(err)
            return
          }

          alert(payload.nonce)
        })
    })
  }
```

**Comment by SamVerschueren** [comment]
Have you tried `pify(dropIn.requestPaymentMethod.bind(dropIn))`?

**Comment by manuelnaturalcycles** [comment]
perfect! i kinda guesses it was something related to this, sorry for bothering guys, thanks for the help
