### ISSUE TITLE
feature: all bind-all when passed an object

### ISSUE THREAD

**Issue by kumavis** [sindresorhus/pify#48]
pify has a nice feature where you can promisify an obj's methods

example from readme:
```js
// Promisify all methods in a module
pify(fs).readFile('package.json', 'utf8').then(data => {
	console.log(JSON.parse(data).name);
	//=> 'pify'
});
```

however this doesnt work when the child methods expect a reference to the owning object

example from my experience:
```js
const Client = require('coinbase').Client
const pify = require('pify')

const client = pify(new Client({}))
const accounts = await client.getAccounts(null) // fails due to unset `this` reference
```

work around - use `bind-all`:
```js
const Client = require('coinbase').Client
const pify = require('pify')
const bindAll = require('bind-all')

const client = pify(bindAll(new Client({})))
const accounts = await client.getAccounts(null)
```

**Comment by doasync** [comment]
You can just use **[doasync](https://www.npmjs.com/package/doasync)** npm module with node 8.

It's like pify, but uses **util.promisify**, **Proxy** and **WeakMaps** (for memoization). It should be fast...

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/pify/pull/73.
