### ISSUE TITLE
Please consider the behavior with multiple parameters

### ISSUE THREAD

**Issue by julien-f** [sindresorhus/pify#5]
See petkaantonov/bluebird#307 for more info.

**Comment by sindresorhus** [comment]
Ah, damn. I was very sceptical about adding that, but I ironically wanted to align with Bluebird... I also didn't think of the case were a sub-dependency changes callback argument arity in a patch/minor release. Fixed now though. I went with the same option name as in Bluebird 3.0, `multiArgs: true`. Thanks for posting this issue. :)

**Comment by julien-f** [comment]
Thank you :)
