### ISSUE TITLE
Failed to minify code with webpack 3

### ISSUE THREAD

**Issue by dziamid** [sindresorhus/pify#50]
Webpack production build fails with error:

```
Failed to minify the code from this file: 
 	./node_modules/pify/index.js:3 
```
How to reproduce. 
Create an app using react-create-app, use pify in the codebase and run `yarn build`

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
