### ISSUE TITLE
Error in line: for (const key in obj)

### ISSUE THREAD

**Issue by AleCaste** [sindresorhus/pify#51]
Hello, the line 78 that says:
```for (const key in obj) {```
... should be rewritten to...
```for (var key in obj) {```
... since ```key``` will change within the loop.
Otherwise some browsers like old versions of Firefox will throw the error: ```SyntaxError: missing = in const declaration```

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
