### ISSUE TITLE
Rethink your usage of pinkie-promise

### ISSUE THREAD

**Issue by czuendorf** [sindresorhus/pify#53]
Yesterday, there was a big issue because the developer of pinkie-promise deleted his project on npm.

https://github.com/npm/registry/issues/255
https://news.ycombinator.com/item?id=16087024

I would propose that you get rid of this dependency.

**Comment by sindresorhus** [comment]
> Yesterday, there was a big issue because the developer of pinkie-promise deleted his project on npm.

You don't know that yet. All we know is that the account disappeared. It could have been an npm bug or something malicious.

**Comment by czuendorf** [comment]
All that trouble, because of this line?

https://github.com/floatdrop/pinkie-promise/blob/master/index.js

**Comment by sindresorhus** [comment]
I don't think you understand what happened. Please read the incident report. It could have happened to any module.

**Comment by czuendorf** [comment]
Because of this dependency line, i was unable to install Lerna.

http://npm.anvaka.com/#/view/2d/lerna

**Comment by sindresorhus** [comment]
Closing as it's fixed by npm and not relevant to this project at all. Take the discussion elsewhere :)
