### ISSUE TITLE
pify(setTimeout) does not work correctly in Node.js

### ISSUE THREAD

**Issue by feross** [sindresorhus/pify#56]
This works with `util.promisify()`:

```js
const { promisify } = require('util')
const setTimeoutAsync = promisify(setTimeout)

async function init () {
  console.log('Waiting 5 seconds...')
  await setTimeoutAsync(5000)
  console.log('Done!')
}

init()
```

It would be nice if it worked with `pify()` too!

Not sure if this requires using `util.promisify()` when running in Node.js, as described in https://github.com/sindresorhus/pify/issues/41 or if it can just be implemented by reading the `util.promisify.custom` symbol on the function, as described in the Node.js docs: https://nodejs.org/api/util.html#util_custom_promisified_functions

**Comment by sindresorhus** [comment]
If you want magic behavior like that, I think it's better to just use  `util.promisify` directly. I mostly use `util.promisify` these days.
