### ISSUE TITLE
TypeError when passing undefined or null

### ISSUE THREAD

**Issue by Mottie** [sindresorhus/pify#58]
[Line 75](https://github.com/sindresorhus/pify/blob/master/index.js#L75) is throwing a JS error when `undefined` or `null` is passed to the function.

> TypeError: Cannot convert undefined or null to object

I was going to submit a PR with this change to the line:

```js
ret = Object.create(Object.getPrototypeOf(obj || {}));
```

and these tests:

```js
test('return empty object with falsy values', t => {
	t.is(typeof m(), 'object');
	t.is(typeof m(''), 'object');
	t.is(typeof m(null), 'object');
});
```

But, I wasn't sure if you wanted to return the original parameter, or an empty object. And, I couldn't get the optimization test to pass

**Comment by sindresorhus** [comment]
We shouldn't silently handle invalid input. I would accept a PR adding a type check at the top of the function that throws a `TypeError` on invalid input.

**Comment by weisssean** [comment]
When is this fix going to be released?

**Comment by Mottie** [comment]
Fixed in #59! 🎉

**Comment by noalevit18** [comment]
@Mottie 
The lastest npm version doesn't contain this fix. When a new version should be released?

**Comment by Mottie** [comment]
Npm is showing the latest version (3.0.0). Oddly, it's reporting the publish date as [5/28/2017, 1:25:28 AM](https://www.npmjs.com/package/pify) (in the tooltip) and not [May 2018](https://github.com/sindresorhus/pify/commit/9ef944cf168cb589b611c48f5ef06bd5ea736a3c).

**Comment by noalevit18** [comment]
Github also shows that the lastest version is from May 28, 2017

**Comment by Mottie** [comment]
Sorry, you're right. It hasn't been released (I need my caffeine). That's up to @sindresorhus then.
