### ISSUE TITLE
Support context

### ISSUE THREAD

**Issue by dsblv** [sindresorhus/pify#6]
As far as I can get, right now the only way to carry the context through pify is to explicitly `.bind()` it:

```js
var promise = pify(obj.method.bind(obj))(args);
```

This is all cool and native, but wouldn't it be more clean to make `context` an option:

```js
var promise = pify(obj.method, {context: obj})(args);
```

Especially when one wants to save `opts` somewhere and pify several methods of one object?

This is more of a question than request, although I could make a PR if it souds like a good idea :smirk:

**Comment by dsblv** [comment]
`pify.all()` is super useful untill you have to deal with external module with some *unpifiable* methods.

**Comment by sindresorhus** [comment]
I don't see the point when you can use `.bind()`. Binding is the correct way to do it and more explicit.

> but wouldn't it be more clean 

I find `.bind` more clean.

**Comment by sindresorhus** [comment]
> pify.all() is super useful untill you have to deal with external module with some unpifiable methods.

Can you elaborate? Might be something that can be done about that ;)

**Comment by dsblv** [comment]
The problem is that we can't say if the function will ever call the callback that pify attaches to `arguments`, right?

So the only way I see is to filter methods manually. Question is: what is the better way to do this (for consumers)?

```js
var pifiedObj = pify.all(obj, {
  include: ['some', 'good', 'methods'],
  exclude: ['bad', 'ones']
});
```

What do you think?

**Comment by sindresorhus** [comment]
I've looked at the Bluebird promisify code and it tries to infer using magic, but I'd rather it be explicit.

Your suggestion looks good. Wanna do a PR? Include and exclude should be mutually exclusive.

**Comment by dsblv** [comment]
Yes, I'm in, thanks!

**Comment by jdalton** [comment]
Related to #27?
