### ISSUE TITLE
Major release without release notes?

### ISSUE THREAD

**Issue by limonte** [sindresorhus/pify#66]
Major release means "THERE ARE BREAKING CHANGES". Where devs can read about those? There's nor release notes in https://github.com/sindresorhus/pify/releases/tag/v4.0.0 neither `CHANGELOG.md` file.

**Comment by sindresorhus** [comment]
I did it at some point, but forgot to answer this issue: https://github.com/sindresorhus/pify/releases/tag/v4.0.0
