### ISSUE TITLE
multiArgs for only some methods on a module/object

### ISSUE THREAD

**Issue by daytonlowell** [sindresorhus/pify#77]
Currently if you pass `{ multiArgs: true }`, all methods will resolve to an array. But, sometimes you might want to just have some of the methods resolve to the array while others resolve to a single value.

Here's a real world example: 
In [mysql](https://github.com/mysqljs/mysql#pooling-connections) a created pool has a `getConnection` method, and a `query` method. The callback for `getConnection` only has a single argument, while `query` has 2(`results` & `fields`).

The consumer can array destructure easy enough.
```js
const [ connection ] = await pool.getConnection()
```

But it requires more work than what they probably expect.
```js
const connection = await pool.getConnection()
```

If there's interest in dealing with this, I imagine `multiArgs` being able to take an array of strings(method names). And those methods would resolve to an array of values, and all other methods would return a single value, as is the default.

Thoughts?

**Comment by daytonlowell** [comment]
Issue #45 talked about doing it automatically, and the dangers of it.

**Comment by sindresorhus** [comment]
I think this is too much of an obscure use-case to support. You can just iterate the methods yourself and use Pify in the loop.

**Comment by daytonlowell** [comment]
Totally fair. Thanks.
