### ISSUE TITLE
Please bind the function

### ISSUE THREAD

**Issue by jcalfee** [sindresorhus/pify#79]
Could you please add a bind to the wrapped function so `this` will work?

**Comment by jcalfee** [comment]
On second thought, I guess you can't do that.  You don't have access to the parent object.

I went down this rabbit hole, because the API I'm using has nested objects off of their main API and pify does not seem to have a method to step into and promisify those functions.  So, attempting to bind a nested function broke the API because `this` was undefined.  So I guess I need to iterate those objects and apply pify to each one.

**Comment by jcalfee** [comment]
If I try to promisify each function, this is what I have to do:
```js
await pify(sdk.billingPlan.list.bind(sdk.billingPlan))()
```
Seems like there should be a better way:
```js
pify(sdk.billingPlan, 'list')()
```

**Comment by sindresorhus** [comment]
@jcalfee See: https://github.com/sindresorhus/pify/pull/78 I don't think we want to add such an API. You can just do `pify(sdk.billingPlan).list()`.
