### ISSUE TITLE
Edge case: pify.all() when module is a function

### ISSUE THREAD

**Issue by dsblv** [sindresorhus/pify#8]
I noticed that when pify promisifies a module, it stores methods in newly-created object. This means if the module is a function with attached methods (like pify itself), `pify.all()` promicifies methods, but loses the main function.

```js
function fn(x, cb) {
	setImmediate(function () {
		cb(null, x);
	});
}

fn.meow = function (cb) {
	setImmediate(function () {
		cb(null, 'meow');
	});
};

var pfn = pify.all(fn);

pfn.meow().then(function (data) {
	console.log(data);
	//=> 'meow'
});

pfn('hi').then();
//=> nope, pfn is not a function
```

**Comment by sindresorhus** [comment]
I guess we could [clone it](https://gist.github.com/Sykkro/7490193) if it's a function.

// @dsblv Thoughts?

**Comment by dsblv** [comment]
This is exactly what I was thinking about.

One thing: how to tell pify whether it should process that function or not? Add another option? Or some magic word to look for in `include/exclude` array?

**Comment by sindresorhus** [comment]
An option would be best.
