### ISSUE TITLE
Support functions with seperate success and error callbacks

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/pify#81]
This is especially useful when using https://github.com/jquery/jquery or https://github.com/audiojs/web-audio-api

```js
const pify = require('pify');

const someFunction = (data, successCallback, errorCallback) => {
    // Process data...
}

(async () => {
	const data = await pify(someFunction)('some data');

	console.log(data);
})();
```

// @sindresorhus

**Comment by sindresorhus** [comment]
That's too much of an edge-case than what I'm willing to support. You could wrap it in a function that creates the normal callback API or you could create a `pify` wrapper package for this specific use-case.
